# 名称及版本号
main:
  name: ywutil
  version: v1.0.0

# 当前服务器IP及名称
server:
  ip: 0.0.0.0
  name: server_name

# web服务器端口号
web:
  port: 8888

# 监控时间间隔
monitor:
  interval: 60

# 队列地址
queue:
  url: amqp://admin:admin@47.75.103.32:5672/